// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/post/:postId": {
    params: {
      "postId": string;
    };
  };
  "/ponggame": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/games": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/dashboard/finances": {
    params: {};
  };
  "/dashboard/personal-info": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/post/:postId" | "/ponggame" | "/login" | "/games" | "/dashboard" | "/dashboard/finances" | "/dashboard/personal-info";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/post.tsx": {
    id: "routes/post";
    page: "/post/:postId";
  };
  "routes/pong-game.tsx": {
    id: "routes/pong-game";
    page: "/ponggame";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/games.tsx": {
    id: "routes/games";
    page: "/games";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard" | "/dashboard/finances" | "/dashboard/personal-info";
  };
  "routes/finanes.tsx": {
    id: "routes/finanes";
    page: "/dashboard/finances";
  };
  "routes/personal-info.tsx": {
    id: "routes/personal-info";
    page: "/dashboard/personal-info";
  };
};