# Generated by Django 5.2.4 on 2025-08-10 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_alter_post_money"),
    ]

    operations = [
        migrations.CreateModel(
            name="Token",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("token", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
                ("user_id", models.IntegerField()),
                ("is_used", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="country",
            field=models.CharField(default="america", max_length=63),
        ),
        migrations.AddField(
            model_name="post",
            name="phone",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
