# Generated by Django 5.2.4 on 2025-08-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_token_post_country_post_phone_alter_post_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
