# Generated by Django 5.2.6 on 2025-09-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_country_alter_post_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='credits',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
    ]
