# Generated by Django 5.2.6 on 2025-09-07 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='credits',
            field=models.DecimalField(decimal_places=0, default=50, max_digits=20),
        ),
    ]
