# Generated by Django 5.2.6 on 2025-09-10 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='prizes_won',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
    ]
