# Generated by Django 5.2.6 on 2025-09-10 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_prizes_won'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='prizes_won',
            field=models.IntegerField(default=0),
        ),
    ]
