# Generated by Django 5.2.6 on 2025-09-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_post_prizes_won'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='credits_spent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='games_played',
            field=models.IntegerField(default=0),
        ),
    ]
