# Generated by Django 5.2.6 on 2025-09-11 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_post_credits_spent_post_games_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='email_confirmations_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='promotional_offers_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
